# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SMeter_SA.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(1000, 750)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter_4 = QtWidgets.QSplitter(self.tab)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.splitter = QtWidgets.QSplitter(self.splitter_4)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setMaximumSize(QtCore.QSize(269, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_database_setting = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_database_setting.setFont(font)
        self.pushButton_database_setting.setObjectName("pushButton_database_setting")
        self.verticalLayout.addWidget(self.pushButton_database_setting)
        self.label_Date_table = QtWidgets.QLabel(self.groupBox)
        self.label_Date_table.setObjectName("label_Date_table")
        self.verticalLayout.addWidget(self.label_Date_table)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_2 = QtWidgets.QLabel(self.groupBox)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.DateEdit_table = QtWidgets.QDateEdit(self.groupBox)
        self.DateEdit_table.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateEdit_table.setCalendarPopup(True)
        self.DateEdit_table.setObjectName("DateEdit_table")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateEdit_table)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.pushButton_table = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_table.setFont(font)
        self.pushButton_table.setObjectName("pushButton_table")
        self.verticalLayout.addWidget(self.pushButton_table)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(118, 549, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_db_data = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_db_data.setAlternatingRowColors(True)
        self.tableWidget_db_data.setObjectName("tableWidget_db_data")
        self.tableWidget_db_data.setColumnCount(0)
        self.tableWidget_db_data.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_db_data, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.splitter_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.Label = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label.setFont(font)
        self.Label.setObjectName("Label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.ComboBox_SID_plot = QtWidgets.QComboBox(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_SID_plot.sizePolicy().hasHeightForWidth())
        self.ComboBox_SID_plot.setSizePolicy(sizePolicy)
        self.ComboBox_SID_plot.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_SID_plot.setFont(font)
        self.ComboBox_SID_plot.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.ComboBox_SID_plot.setDuplicatesEnabled(False)
        self.ComboBox_SID_plot.setFrame(True)
        self.ComboBox_SID_plot.setObjectName("ComboBox_SID_plot")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.ComboBox_SID_plot.addItem("")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_SID_plot)
        self.horizontalLayout_5.addLayout(self.formLayout_6)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_9.setObjectName("formLayout_9")
        self.Label_8 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_8.setFont(font)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.DateEdit_start_plot = QtWidgets.QDateEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateEdit_start_plot.setFont(font)
        self.DateEdit_start_plot.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateEdit_start_plot.setCalendarPopup(True)
        self.DateEdit_start_plot.setObjectName("DateEdit_start_plot")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateEdit_start_plot)
        self.horizontalLayout_5.addLayout(self.formLayout_9)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_10.setObjectName("formLayout_10")
        self.Label_9 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_9.setFont(font)
        self.Label_9.setObjectName("Label_9")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.DateEdit_end_plot = QtWidgets.QDateEdit(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateEdit_end_plot.setFont(font)
        self.DateEdit_end_plot.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateEdit_end_plot.setCalendarPopup(True)
        self.DateEdit_end_plot.setObjectName("DateEdit_end_plot")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateEdit_end_plot)
        self.horizontalLayout_5.addLayout(self.formLayout_10)
        self.pushButton_plot = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_plot.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_plot.setFont(font)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.horizontalLayout_5.addWidget(self.pushButton_plot)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.widget_plot = QtWidgets.QWidget(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot.sizePolicy().hasHeightForWidth())
        self.widget_plot.setSizePolicy(sizePolicy)
        self.widget_plot.setObjectName("widget_plot")
        self.verticalLayout_5.addWidget(self.widget_plot)
        self.gridLayout_9.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.Label_5 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_5.setFont(font)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.ComboBox_SID_plot_2 = QtWidgets.QComboBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ComboBox_SID_plot_2.sizePolicy().hasHeightForWidth())
        self.ComboBox_SID_plot_2.setSizePolicy(sizePolicy)
        self.ComboBox_SID_plot_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_SID_plot_2.setFont(font)
        self.ComboBox_SID_plot_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.ComboBox_SID_plot_2.setDuplicatesEnabled(False)
        self.ComboBox_SID_plot_2.setFrame(True)
        self.ComboBox_SID_plot_2.setObjectName("ComboBox_SID_plot_2")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.ComboBox_SID_plot_2.addItem("")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_SID_plot_2)
        self.horizontalLayout_6.addLayout(self.formLayout_8)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_11.setObjectName("formLayout_11")
        self.Label_10 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_10.setFont(font)
        self.Label_10.setObjectName("Label_10")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.DateEdit_start_plot_2 = QtWidgets.QDateEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateEdit_start_plot_2.setFont(font)
        self.DateEdit_start_plot_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateEdit_start_plot_2.setCalendarPopup(True)
        self.DateEdit_start_plot_2.setObjectName("DateEdit_start_plot_2")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateEdit_start_plot_2)
        self.horizontalLayout_6.addLayout(self.formLayout_11)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_12.setObjectName("formLayout_12")
        self.Label_11 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_11.setFont(font)
        self.Label_11.setObjectName("Label_11")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.DateEdit_end_plot_2 = QtWidgets.QDateEdit(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateEdit_end_plot_2.setFont(font)
        self.DateEdit_end_plot_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateEdit_end_plot_2.setCalendarPopup(True)
        self.DateEdit_end_plot_2.setObjectName("DateEdit_end_plot_2")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateEdit_end_plot_2)
        self.horizontalLayout_6.addLayout(self.formLayout_12)
        self.pushButton_plot_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_plot_2.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_plot_2.setFont(font)
        self.pushButton_plot_2.setObjectName("pushButton_plot_2")
        self.horizontalLayout_6.addWidget(self.pushButton_plot_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.widget_plot_2 = QtWidgets.QWidget(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot_2.sizePolicy().hasHeightForWidth())
        self.widget_plot_2.setSizePolicy(sizePolicy)
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.verticalLayout_6.addWidget(self.widget_plot_2)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.Label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_4.setFont(font)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.ComboBox_SID_hist = QtWidgets.QComboBox(self.tab_3)
        self.ComboBox_SID_hist.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_SID_hist.setFont(font)
        self.ComboBox_SID_hist.setObjectName("ComboBox_SID_hist")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.ComboBox_SID_hist.addItem("")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_SID_hist)
        self.horizontalLayout.addLayout(self.formLayout_7)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_3 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_3.setFont(font)
        self.Label_3.setObjectName("Label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.DateTimeEdit_start_hist = QtWidgets.QDateTimeEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateTimeEdit_start_hist.setFont(font)
        self.DateTimeEdit_start_hist.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_start_hist.setCalendarPopup(True)
        self.DateTimeEdit_start_hist.setObjectName("DateTimeEdit_start_hist")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_start_hist)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName("formLayout_4")
        self.Label_6 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_6.setFont(font)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.DateTimeEdit_end_hist = QtWidgets.QDateTimeEdit(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateTimeEdit_end_hist.setFont(font)
        self.DateTimeEdit_end_hist.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(23, 59, 59)))
        self.DateTimeEdit_end_hist.setCalendarPopup(True)
        self.DateTimeEdit_end_hist.setObjectName("DateTimeEdit_end_hist")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_end_hist)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.pushButton_hist = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_hist.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_hist.setFont(font)
        self.pushButton_hist.setObjectName("pushButton_hist")
        self.horizontalLayout.addWidget(self.pushButton_hist)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget_hist = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_hist.sizePolicy().hasHeightForWidth())
        self.widget_hist.setSizePolicy(sizePolicy)
        self.widget_hist.setObjectName("widget_hist")
        self.verticalLayout_3.addWidget(self.widget_hist)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setObjectName("formLayout_13")
        self.Label_7 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_7.setFont(font)
        self.Label_7.setObjectName("Label_7")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.ComboBox_SID_hist_2 = QtWidgets.QComboBox(self.tab_6)
        self.ComboBox_SID_hist_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.ComboBox_SID_hist_2.setFont(font)
        self.ComboBox_SID_hist_2.setObjectName("ComboBox_SID_hist_2")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.ComboBox_SID_hist_2.addItem("")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComboBox_SID_hist_2)
        self.horizontalLayout_2.addLayout(self.formLayout_13)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_5.setObjectName("formLayout_5")
        self.Label_12 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_12.setFont(font)
        self.Label_12.setObjectName("Label_12")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.DateTimeEdit_start_hist_2 = QtWidgets.QDateTimeEdit(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateTimeEdit_start_hist_2.setFont(font)
        self.DateTimeEdit_start_hist_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(0, 0, 0)))
        self.DateTimeEdit_start_hist_2.setCalendarPopup(True)
        self.DateTimeEdit_start_hist_2.setObjectName("DateTimeEdit_start_hist_2")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_start_hist_2)
        self.horizontalLayout_2.addLayout(self.formLayout_5)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_14.setObjectName("formLayout_14")
        self.Label_13 = QtWidgets.QLabel(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Label_13.setFont(font)
        self.Label_13.setObjectName("Label_13")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.DateTimeEdit_end_hist_2 = QtWidgets.QDateTimeEdit(self.tab_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.DateTimeEdit_end_hist_2.setFont(font)
        self.DateTimeEdit_end_hist_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(23, 59, 59)))
        self.DateTimeEdit_end_hist_2.setCalendarPopup(True)
        self.DateTimeEdit_end_hist_2.setObjectName("DateTimeEdit_end_hist_2")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DateTimeEdit_end_hist_2)
        self.horizontalLayout_2.addLayout(self.formLayout_14)
        self.pushButton_hist_2 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_hist_2.setMaximumSize(QtCore.QSize(240, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_hist_2.setFont(font)
        self.pushButton_hist_2.setObjectName("pushButton_hist_2")
        self.horizontalLayout_2.addWidget(self.pushButton_hist_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.widget_hist_2 = QtWidgets.QWidget(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_hist_2.sizePolicy().hasHeightForWidth())
        self.widget_hist_2.setSizePolicy(sizePolicy)
        self.widget_hist_2.setObjectName("widget_hist_2")
        self.verticalLayout_4.addWidget(self.widget_hist_2)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能电表检定误差计算系统"))
        self.groupBox.setTitle(_translate("MainWindow", "设置"))
        self.pushButton_database_setting.setText(_translate("MainWindow", "数据库配置"))
        self.label_Date_table.setText(_translate("MainWindow", "当前日期："))
        self.Label_2.setText(_translate("MainWindow", "日期"))
        self.DateEdit_table.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.pushButton_table.setText(_translate("MainWindow", "显示数据"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据表显示"))
        self.label.setText(_translate("MainWindow", "基于检定数据的流水线状态评估工具"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "单日评估"))
        self.Label.setText(_translate("MainWindow", "单元号"))
        self.ComboBox_SID_plot.setItemText(0, _translate("MainWindow", "总视图"))
        self.ComboBox_SID_plot.setItemText(1, _translate("MainWindow", "1"))
        self.ComboBox_SID_plot.setItemText(2, _translate("MainWindow", "2"))
        self.ComboBox_SID_plot.setItemText(3, _translate("MainWindow", "3"))
        self.ComboBox_SID_plot.setItemText(4, _translate("MainWindow", "4"))
        self.ComboBox_SID_plot.setItemText(5, _translate("MainWindow", "5"))
        self.ComboBox_SID_plot.setItemText(6, _translate("MainWindow", "6"))
        self.ComboBox_SID_plot.setItemText(7, _translate("MainWindow", "7"))
        self.ComboBox_SID_plot.setItemText(8, _translate("MainWindow", "8"))
        self.ComboBox_SID_plot.setItemText(9, _translate("MainWindow", "9"))
        self.ComboBox_SID_plot.setItemText(10, _translate("MainWindow", "10"))
        self.ComboBox_SID_plot.setItemText(11, _translate("MainWindow", "11"))
        self.ComboBox_SID_plot.setItemText(12, _translate("MainWindow", "12"))
        self.ComboBox_SID_plot.setItemText(13, _translate("MainWindow", "13"))
        self.ComboBox_SID_plot.setItemText(14, _translate("MainWindow", "14"))
        self.ComboBox_SID_plot.setItemText(15, _translate("MainWindow", "15"))
        self.ComboBox_SID_plot.setItemText(16, _translate("MainWindow", "16"))
        self.ComboBox_SID_plot.setItemText(17, _translate("MainWindow", "17"))
        self.ComboBox_SID_plot.setItemText(18, _translate("MainWindow", "18"))
        self.ComboBox_SID_plot.setItemText(19, _translate("MainWindow", "19"))
        self.ComboBox_SID_plot.setItemText(20, _translate("MainWindow", "20"))
        self.Label_8.setText(_translate("MainWindow", "起"))
        self.DateEdit_start_plot.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.Label_9.setText(_translate("MainWindow", "止"))
        self.DateEdit_end_plot.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.pushButton_plot.setText(_translate("MainWindow", "显示图像"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "误差曲线1"))
        self.Label_5.setText(_translate("MainWindow", "单元号"))
        self.ComboBox_SID_plot_2.setItemText(0, _translate("MainWindow", "总视图"))
        self.ComboBox_SID_plot_2.setItemText(1, _translate("MainWindow", "1"))
        self.ComboBox_SID_plot_2.setItemText(2, _translate("MainWindow", "2"))
        self.ComboBox_SID_plot_2.setItemText(3, _translate("MainWindow", "3"))
        self.ComboBox_SID_plot_2.setItemText(4, _translate("MainWindow", "4"))
        self.ComboBox_SID_plot_2.setItemText(5, _translate("MainWindow", "5"))
        self.ComboBox_SID_plot_2.setItemText(6, _translate("MainWindow", "6"))
        self.ComboBox_SID_plot_2.setItemText(7, _translate("MainWindow", "7"))
        self.ComboBox_SID_plot_2.setItemText(8, _translate("MainWindow", "8"))
        self.ComboBox_SID_plot_2.setItemText(9, _translate("MainWindow", "9"))
        self.ComboBox_SID_plot_2.setItemText(10, _translate("MainWindow", "10"))
        self.ComboBox_SID_plot_2.setItemText(11, _translate("MainWindow", "11"))
        self.ComboBox_SID_plot_2.setItemText(12, _translate("MainWindow", "12"))
        self.ComboBox_SID_plot_2.setItemText(13, _translate("MainWindow", "13"))
        self.ComboBox_SID_plot_2.setItemText(14, _translate("MainWindow", "14"))
        self.ComboBox_SID_plot_2.setItemText(15, _translate("MainWindow", "15"))
        self.ComboBox_SID_plot_2.setItemText(16, _translate("MainWindow", "16"))
        self.ComboBox_SID_plot_2.setItemText(17, _translate("MainWindow", "17"))
        self.ComboBox_SID_plot_2.setItemText(18, _translate("MainWindow", "18"))
        self.ComboBox_SID_plot_2.setItemText(19, _translate("MainWindow", "19"))
        self.ComboBox_SID_plot_2.setItemText(20, _translate("MainWindow", "20"))
        self.Label_10.setText(_translate("MainWindow", "起"))
        self.DateEdit_start_plot_2.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.Label_11.setText(_translate("MainWindow", "止"))
        self.DateEdit_end_plot_2.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.pushButton_plot_2.setText(_translate("MainWindow", "显示图像"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "误差曲线2"))
        self.Label_4.setText(_translate("MainWindow", "单元号"))
        self.ComboBox_SID_hist.setItemText(0, _translate("MainWindow", "总视图"))
        self.ComboBox_SID_hist.setItemText(1, _translate("MainWindow", "1"))
        self.ComboBox_SID_hist.setItemText(2, _translate("MainWindow", "2"))
        self.ComboBox_SID_hist.setItemText(3, _translate("MainWindow", "3"))
        self.ComboBox_SID_hist.setItemText(4, _translate("MainWindow", "4"))
        self.ComboBox_SID_hist.setItemText(5, _translate("MainWindow", "5"))
        self.ComboBox_SID_hist.setItemText(6, _translate("MainWindow", "6"))
        self.ComboBox_SID_hist.setItemText(7, _translate("MainWindow", "7"))
        self.ComboBox_SID_hist.setItemText(8, _translate("MainWindow", "8"))
        self.ComboBox_SID_hist.setItemText(9, _translate("MainWindow", "9"))
        self.ComboBox_SID_hist.setItemText(10, _translate("MainWindow", "10"))
        self.ComboBox_SID_hist.setItemText(11, _translate("MainWindow", "11"))
        self.ComboBox_SID_hist.setItemText(12, _translate("MainWindow", "12"))
        self.ComboBox_SID_hist.setItemText(13, _translate("MainWindow", "13"))
        self.ComboBox_SID_hist.setItemText(14, _translate("MainWindow", "14"))
        self.ComboBox_SID_hist.setItemText(15, _translate("MainWindow", "15"))
        self.ComboBox_SID_hist.setItemText(16, _translate("MainWindow", "16"))
        self.ComboBox_SID_hist.setItemText(17, _translate("MainWindow", "17"))
        self.ComboBox_SID_hist.setItemText(18, _translate("MainWindow", "18"))
        self.ComboBox_SID_hist.setItemText(19, _translate("MainWindow", "19"))
        self.ComboBox_SID_hist.setItemText(20, _translate("MainWindow", "20"))
        self.Label_3.setText(_translate("MainWindow", "起"))
        self.DateTimeEdit_start_hist.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.Label_6.setText(_translate("MainWindow", "止"))
        self.DateTimeEdit_end_hist.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.pushButton_hist.setText(_translate("MainWindow", "显示图像"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "误差分布1"))
        self.Label_7.setText(_translate("MainWindow", "单元号"))
        self.ComboBox_SID_hist_2.setItemText(0, _translate("MainWindow", "总视图"))
        self.ComboBox_SID_hist_2.setItemText(1, _translate("MainWindow", "1"))
        self.ComboBox_SID_hist_2.setItemText(2, _translate("MainWindow", "2"))
        self.ComboBox_SID_hist_2.setItemText(3, _translate("MainWindow", "3"))
        self.ComboBox_SID_hist_2.setItemText(4, _translate("MainWindow", "4"))
        self.ComboBox_SID_hist_2.setItemText(5, _translate("MainWindow", "5"))
        self.ComboBox_SID_hist_2.setItemText(6, _translate("MainWindow", "6"))
        self.ComboBox_SID_hist_2.setItemText(7, _translate("MainWindow", "7"))
        self.ComboBox_SID_hist_2.setItemText(8, _translate("MainWindow", "8"))
        self.ComboBox_SID_hist_2.setItemText(9, _translate("MainWindow", "9"))
        self.ComboBox_SID_hist_2.setItemText(10, _translate("MainWindow", "10"))
        self.ComboBox_SID_hist_2.setItemText(11, _translate("MainWindow", "11"))
        self.ComboBox_SID_hist_2.setItemText(12, _translate("MainWindow", "12"))
        self.ComboBox_SID_hist_2.setItemText(13, _translate("MainWindow", "13"))
        self.ComboBox_SID_hist_2.setItemText(14, _translate("MainWindow", "14"))
        self.ComboBox_SID_hist_2.setItemText(15, _translate("MainWindow", "15"))
        self.ComboBox_SID_hist_2.setItemText(16, _translate("MainWindow", "16"))
        self.ComboBox_SID_hist_2.setItemText(17, _translate("MainWindow", "17"))
        self.ComboBox_SID_hist_2.setItemText(18, _translate("MainWindow", "18"))
        self.ComboBox_SID_hist_2.setItemText(19, _translate("MainWindow", "19"))
        self.ComboBox_SID_hist_2.setItemText(20, _translate("MainWindow", "20"))
        self.Label_12.setText(_translate("MainWindow", "起"))
        self.DateTimeEdit_start_hist_2.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.Label_13.setText(_translate("MainWindow", "止"))
        self.DateTimeEdit_end_hist_2.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.pushButton_hist_2.setText(_translate("MainWindow", "显示图像"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "误差分布2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "状态评估"))

